/**
 * NOTE: This class is auto generated by the swagger code generator program (unset).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.myworks.creation.kheloswag.controller;

import com.myworks.creation.kheloswag.model.BookingError;
import com.myworks.creation.kheloswag.model.NewBookingList;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Optional;

@Api(value = "MyBookingLists", description = "the MyBookingLists API")
public interface MyBookingListsApi {

    Logger log = LoggerFactory.getLogger(MyBookingListsApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "List of Bookings for particular User", nickname = "getBookingListForUserId", notes = "", response = NewBookingList.class, tags={ "My Booking lists", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = NewBookingList.class),
        @ApiResponse(code = 500, message = "successful operation", response = BookingError.class) })
    @RequestMapping(value = "/v1/bookings/{userId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<NewBookingList> _getBookingListForUserId(@ApiParam(value = "ID of User to return list of bookings",required=true) @PathVariable("userId") String userId) {
        return getBookingListForUserId(userId);
    }

    // Override this method
    default ResponseEntity<NewBookingList> getBookingListForUserId(String userId) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"bookingsList\" : [ {    \"gameId\" : \"1\",    \"districtName\" : \"Chandigarh\",    \"gameName\" : \"Volley ball\",    \"stateName\" : \"Punjab\",    \"gameStartTime\" : \"2019-10-11\",    \"gameEndTime\" : \"2019-10-11\",    \"userId\" : \"123\",    \"bookingId\" : \"123\",    \"groundName\" : \"ZPH - Villur\"  }, {    \"gameId\" : \"1\",    \"districtName\" : \"Chandigarh\",    \"gameName\" : \"Volley ball\",    \"stateName\" : \"Punjab\",    \"gameStartTime\" : \"2019-10-11\",    \"gameEndTime\" : \"2019-10-11\",    \"userId\" : \"123\",    \"bookingId\" : \"123\",    \"groundName\" : \"ZPH - Villur\"  } ]}", NewBookingList.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default MyBookingListsApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
