/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.myworks.creation.kheloswag.controller;

import com.myworks.creation.kheloswag.model.StateError;
import com.myworks.creation.kheloswag.model.States;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Optional;

@Api(value = "StateList", description = "the StateList API")
public interface StateListApi {

    Logger log = LoggerFactory.getLogger(StateListApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "List of states in india", nickname = "getStatesList", notes = "", response = States.class, tags={ "state list", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = States.class),
        @ApiResponse(code = 500, message = "successful operation", response = StateError.class) })
    @RequestMapping(value = "/v1/states",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<States> _getStatesList() {
        return getStatesList();
    }

    // Override this method
    default ResponseEntity<States> getStatesList() {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"statesList\" : [ {    \"creationTime\" : \"Orissa\",    \"stateName\" : \"Orissa\",    \"modificationTime\" : \"Orissa\",    \"stateId\" : 1  }, {    \"creationTime\" : \"Orissa\",    \"stateName\" : \"Orissa\",    \"modificationTime\" : \"Orissa\",    \"stateId\" : 1  } ]}", States.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default StateListApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
